# Generated by Django 3.1.3 on 2020-12-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickAppDemo', '0002_user_is_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='customer_status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_store',
            field=models.BooleanField(default=False, verbose_name='store_status'),
        ),
    ]
