# Generated by Django 3.1.3 on 2020-12-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickAppDemo', '0004_auto_20201204_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
    ]
