# Generated by Django 3.1.3 on 2020-12-15 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PickAppDemo', '0005_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='store',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='order_store', to='PickAppDemo.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
