# Generated by Django 3.1.3 on 2020-12-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickAppDemo', '0007_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
